# Generated by Django 3.0.8 on 2021-03-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(upload_to='post_media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(upload_to='post_media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
