# Generated by Django 3.0.8 on 2021-03-31 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210327_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='media_num',
            new_name='media_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_num',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follower_num',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following_num',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post_num',
        ),
    ]
