# Generated by Django 3.0.8 on 2021-04-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210331_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(null=True, upload_to='post_media'),
        ),
    ]
