# Generated by Django 3.2.3 on 2021-05-22 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_followed_user_id_follow_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='media_file',
            field=models.FileField(upload_to='content_media'),
        ),
        migrations.AlterField(
            model_name='content',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(upload_to='content_media'),
        ),
    ]
